---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    uses: lpenz/omnilint/.github/workflows/omnilint.yml@v0.5.1
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          path: ghaction-python-stdeb
      - uses: actions/checkout@v3.1.0
        with:
          repository: lpenz/ftpsmartsync
          path: ftpsmartsync
      - uses: ./ghaction-python-stdeb
        with:
          working_directory: ftpsmartsync
      - name: check debian packages
        run: |
          set -e -x
          dpkg --info ftpsmartsync/*.deb
          dpkg --contents ftpsmartsync/*.deb
  publish-dockerhub:
    needs: [ omnilint, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.12.0
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.version.outputs.version_docker_ci != 'null'
      - uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ steps.version.outputs.version_docker_ci != 'null' }}
          tags: ${{ github.repository }}:${{ steps.version.outputs.version_docker_ci }}
  publish-github-release:
    needs: [ omnilint, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.12.0
      - name: publish github release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        if: steps.version.outputs.version_tagged != ''
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
